#!/usr/bin/env bash

# Determine the root
if [ -z "$1" ]; then
    u_root=$(./ursa--detect)
else
    u_root=$1
fi

# Mount
./ursa--mount ${u_root}

echo "Opening the vault directory..."
xdg-open /mnt/vault
